name: CommandOverride
version: ${project.version}
author: mrCookieSlime
website: http://TheBusyBiscuit.github.io/

main: me.mrCookieSlime.CommandOverride.main

api-version: 1.13

softdepend: [Vault, PrisonGems, CS-CoreLib]

commands:
  reloadcommands:
    usage: /reloadcommands
    description: Reloads the CommandOverride config

permissions:
  CommandOverride.reload:
    default: op
    description: Allows you to reload the config